### PR TITLE
Update translation

### PR DESCRIPTION
**Pull request by PtilopsisLeucotis**
1. Marked untranslatable string as translatable="false"
2. Updated Russian translation

### CODE REVIEW

**Comment by markusfisch** [comment]
Thanks a lot! 👍

I'm just wondering why you added `translatable="false"` to `donottranslate.xml` 🤔 `donottranslate.xml` is the recommendation for multiple non-translateable strings:
http://tools.android.com/recent/non-translatablestrings

Do I miss something something?

**Comment by PtilopsisLeucotis** [comment]
It is not obligatory, but I have added these marks for additional convenience. Some people use Android Studio Translation Editor for translating apps. If string have mark translatable="false" in xml file, in Translation Editor this string will have check box "Untranslatable" as checked. I think, it will be more unambiguously, that need not translate this string.

**Comment by markusfisch** [comment]
I see, so the Translation Editor doesn't know `donottranslate.xml` 😬 Wasn't aware of that.

Thanks again for contributing! 😄

**Comment by PtilopsisLeucotis** [comment]
You're welcome! 😉

**Pull request merged**
