### PR TITLE
Add arabic localization

### PR DESCRIPTION
**Pull request by ahmed-0011**

### CODE REVIEW

**Comment by markusfisch** [comment]
Thank you 👍

**Comment by markusfisch** [comment]
One last thing: Lint complains about missing quantity translations for `barcode_info`:

image

Can you help me there?

**Comment by ahmed-0011** [comment]
Hi @markusfisch,

Please check the new changes for plurals tag in this commit: #498.

I think this covers every plural case in Arabic. So, please check again, and if you get the same linter error, I think it's safe to just ignore it.

**Comment by ahmed-0011** [comment]
No, "باطل" is too random and is not the correct way to describe "Zero" :)

Zero shares the same plural form with "few", so I used the same string for it. There is another option to translate it to "Empty", but I think translating it to "0 حروف", which is equivalent to "0 characters," is much better.

**Comment by markusfisch** [comment]
Ah, thanks for the clarification and for the quick fix 👍 

I was almost sure that “باطل” wouldn't be the correct translation 🙈  It's always better to ask a native speaker.

**Comment by ahmed-0011** [comment]
I'm looking forward to testing the app with Arabic, and maybe I'll find some localization improvements by interacting with the Arabic interface.

By the way, Arabic is an RTL language, so it's written from right to left. I think Android has good support for RTL languages, but maybe integrating a new language with a unique writing mode is a bit complicated.

I'm available if you have any queries about what the Arabic interface should look like :)

**Pull request merged**
