### PR TITLE
Add Mail, SMS and Telephone action

### PR DESCRIPTION
**Pull request by molikuner**
* Added `SimpleIntentIAction` to simplify code
* Change actions registry Array to Set

### CODE REVIEW

**Comment by molikuner** [comment]
I used the internal icons from Android. Some of those aren't the same white as the others. Should I add custom ones?

**Comment by markusfisch** [comment]
Yes, please. Some device vendors like to customize or enhance the default icons which is quite awful. But please use icons from Google's Material Icons collection if possible.

**Comment by markusfisch** [comment]
And, again, really good work! 👍 Should I wait for the icons with the merge?

**Comment by molikuner** [comment]
Feel free to merge now. :smile:

**Comment by markusfisch** [comment]
Merged 😄

**Pull request merged**
