### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by ss11mik**
Here is a Czech translation as a little 'Thank You' for this app.

### CODE REVIEW

**Comment by markusfisch** [comment]
Thanks a lot 👍

**Comment by markusfisch** [comment]
Just one thing I just noted: Lint is complaining about the missing quantity translation of "few" in
```
	<plurals name="barcode_info">                                                                      
		<item quantity="one">%2$d znak, %1$s</item>
		<item quantity="other">%2$d znaků, %1$s</item>
	</plurals>
```
Is "other" the same as "few" in Czech?

**Comment by ss11mik** [comment]
Sorry, I didn't notice. I also fixed bad indentation now, should I revert this merge and create a new pull request, or which way do you prefer?

**Comment by markusfisch** [comment]
No problem 😄 And thanks again for contributing!

I'd prefer a new pull request since I already merged the first one, if you wouldn't mind 😉

**Comment by ss11mik** [comment]
Sure, I also discovered where the store captions are :facepalm: , so I'll also translate them :smiley:

**Comment by markusfisch** [comment]
This would be great! 👍 😄

**Pull request merged**
