### PR TITLE
Add an intent-filter and a handling method to make user can open image with this app

### PR DESCRIPTION
**Pull request by Noromon**
Rather than decode a image file by "share" only.
This app should be able to decode image files by opening them, too.

I m new to almost EVERYTHING, you may want to have a check. :)

### CODE REVIEW

**Comment by molikuner** [comment]
You copied almost the whole function. That is bad practice. Could you try to reuse some more code? This would simplify the code, make it more readable and even simpler to maintain.

**Comment by Noromon** [comment]
I split a new handleImageUri() from handleSendImage() (and handleOpenImage).
Is that OK now?

**Comment by markusfisch** [comment]
Yes, that's much better! 👍 Thanks for contributing!

If I could just ask for two more little things: would you please apply "Reformat Code" (I suppose you're using Android Studio, it's in the Menu Code -> Reformat Code) and remove the `//Added by` comments (since `git blame` always knows who added what 😉)?

**Comment by Noromon** [comment]
Ok, I ve done that. ;)
But I m a bit afraid of seeing that message "953 lines changed".

**Comment by markusfisch** [comment]
Oh, sorry, this was my fault. I forgot to mention that this project is using tabs instead of spaces for indentation 🙈 To save you from changing it again, I fixed it and merged manually: https://github.com/markusfisch/BinaryEye/commit/6b9e6ee5b4d969caeb7dad0e274d206a98e20bc3

**Comment by markusfisch** [comment]
Thanks again for contributing! 👍

And sorry for using a non-standard indentation.

**Pull request closed without merging**
